import turtle
turtle.bgcolor("Black")
pen1=turtle.Turtle()
pen1.shape("turtle")
pen1.color("Green")
pen1.hideturtle()
pen1.pensize(7)
for i in range(5):
    pen1.pencolor("Orange")
    pen1.forward(10)
    pen1.hideturtle()
    pen1.penup()
    pen1.forward(20)
    pen1.pendown()
    pen1.pencolor("White")
    pen1.forward(10)
    pen1.penup()
    pen1.forward(20)
    pen1.pendown()
pen1.showturtle()
pen1.screen.mainloop()