# Python program to draw car in turtle programming

# Import required library
import turtle

car = turtle.Turtle()

# Below code for drawing rectangular upper body
turtle.bgcolor('Black')
car.color('Red')
car.fillcolor('Orange')
car.pensize(7)
car.penup()
#car.goto(0, 0)
car.pendown()
car.begin_fill()
car.forward(370)
car.left(75)
car.forward(40)
car.lt(65)
car.forward(60)
car.lt(40)
car.forward(240)
car.lt(50)
car.forward(50)
car.rt(45)
car.forward(35)
car.lt(50)
car.forward(50)
car.end_fill()
# Below code for drawing window and roof
car.penup()
car.goto(100, 85)
car.pendown()
car.setheading(45)
car.forward(70)
car.setheading(0)
car.forward(100)
car.setheading(-45)
car.forward(70)
car.setheading(90)
car.penup()
car.goto(200, 85)
car.pendown()
car.forward(49.50)

# Below code for drawing two tyres
car.penup()
car.goto(100, -10)
car.pendown()
car.color('Green')
car.fillcolor('White')
car.begin_fill()
car.circle(20)
car.end_fill()
car.penup()
car.goto(300, -10)
car.pendown()
car.color('Green')
car.fillcolor('White')
car.begin_fill()
car.circle(20)
car.end_fill()
car.hideturtle()
car.screen.mainloop()