#THIS PROGRAM IS SHOW BASICALLY HOW WE MAKE MULTIPLE TURTLE OR PEN USING OOPS CONCEPT...
#IN TURTLE MODULE WE HAVE Turtle CLASS FOR MAKING TURTLE OBJECTS.
import turtle
pen1=turtle.Turtle()
pen1.pensize(7)
pen1.color("red","Blue")
#pen1.fillcolor("Green")
pen1.begin_fill()
pen1.circle(100)
pen1.end_fill()

pen2=turtle.Turtle()
pen2.shape("triangle")
pen2.pensize(7)
pen2.color("black","orange")
pen2.rt(90)
pen2.penup()
pen2.forward(100)
pen2.pendown()
pen2.hideturtle()
pen2.begin_fill()
pen2.circle(100)
pen2.end_fill()
pen2.showturtle()
#turtle.exitonclick()
print(pen1.pos())
print(pen2.pos())
pen2.goto(-18,200)
pen1.screen.mainloop()
